Repository sonic-net/sonic-dhcp-relay, pull requests merged in 2024-12, with the labels that each got.

#51 Clear counter when dhcp6relay init
  src/relay.cpp
  src/relay.h
  test/mock_relay.cpp
Labels: Request for 202405 Branch

#54 [action] [PR:51] Clear counter when dhcp6relay init (#51)
  src/relay.cpp
  src/relay.h
  test/mock_relay.cpp
Labels: automerge

#53 Fail build in PR check when UT fail
  Makefile
Labels: Request for 202311 Branch, Request for 202405 Branch, Request for 202411 Branch
